### ISSUE TITLE
[Feature Request] Multiple Sonarr Support

### ISSUE THREAD

**Issue by Hiren-Z** [CyaOnDaNet/plex_discord_role_management#3]
Some people run multiple Sonarr instances for 4k only or anime.  Would it be able to allow multiple sonarr instances?

**Comment by CyaOnDaNet** [comment]
Support has been added for up to 3 Sonarr instances as of bot [version 1.2.3](https://github.com/CyaOnDaNet/plex_discord_role_management/releases/tag/v1.2.3)
