### ISSUE TITLE
Conatiner Randomly Stops 

### ISSUE THREAD

**Issue by fiservedpi** [CyaOnDaNet/plex_discord_role_management#4]
Here are my logs can see some errors but not sure how those pertain to the container shutting itself down. About every 4-6 hours I'd say.
https://gist.github.com/fiservedpi/0952cf69df06048b31b7d71cf2162a1a

**Comment by CyaOnDaNet** [comment]
That happens to me when discord has an outage, but that is usually only like once a month for me. If it is happening that frequently for you then maybe you have another issue causing discord to be unreachable. I will look into a way to handle this, like a reconnect handler. The last time I looked into this I hit a dead end. For now, you can use the docker flag `--restart always` to make it restart automatically.

**Comment by fiservedpi** [comment]
Great thanks for the info I'll set the flag for now, i was thinking internet outage but I'm not seeing an outage that frequently

**Comment by CyaOnDaNet** [comment]
As of bot v2.0.0 b7a8cca6aa77c5919da062c63bcd96c472af48e4 there is a theoretical fix for this. I have been running it for a while with seemingly no problems so it should be good now. If it ever happens again, I will open this issue back up.
